Repository fga-eps-mds/2020.2-e-Vacina-Frontend, pull requests merged in 2021-05, with the labels that each got.

#39 feat(#149), feat(#148): Update login logic, conecting update, delete and create profile to back-end
  assets/EmptyProfile.png
  lib/controllers/profileController.dart
  lib/controllers/userController.dart
  lib/main.dart
  lib/screens/CreateProfileScreen.dart
  lib/screens/LoginScreen.dart
  lib/screens/MainScreen.dart
  lib/screens/MyWidgets.dart
  lib/screens/RegisterScreen.dart
  lib/screens/UserConfig.dart
  lib/services/api.dart
  pubspec.lock
  pubspec.yaml
Labels: Front-end, Sprint 10, enhancement

#42 feat(#154): adding profilesScreens
  lib/component/ListProfiles.dart
  lib/component/MyWidgets.dart
  lib/controllers/profileController.dart
  lib/controllers/userController.dart
  lib/controllers/vaccineController.dart
  lib/screens/CreateProfileScreen.dart
  lib/screens/LoginScreen.dart
  lib/screens/MainScreen.dart
  lib/screens/ProfilesScreen.dart
  lib/screens/RegisterScreen.dart
  lib/screens/UserConfig.dart
Labels: Development, Front-end, Sprint 10

#49 feat(#171): adding logic to persist login
  lib/component/ListProfiles.dart
  lib/component/MyWidgets.dart
  lib/controllers/profileController.dart
  lib/controllers/userController.dart
  lib/controllers/vaccineController.dart
  lib/globals.dart
  lib/screens/AddVacinaScreen.dart
  lib/screens/CreateProfileScreen.dart
  lib/screens/LoginScreen.dart
  lib/screens/MainScreen.dart
  lib/screens/ProfilesScreen.dart
  lib/screens/SplashScreen.dart
  lib/screens/UserConfig.dart
  lib/screens/adminConfig_screen.dart
  lib/services/api.dart
  pubspec.lock
  pubspec.yaml
  test/profileController_test.dart
Labels: Development, Front-end, Sprint 12

#52 test(#174): correcting user screen
  README.md
  lib/component/MyWidgets.dart
  lib/controllers/userController.dart
  lib/globals.dart
  lib/screens/adminConfig_screen.dart
  lib/services/api.dart
Labels: Front-end, Sprint 12, enhancement
