Repository fga-eps-mds/2020.2-e-Vacina-Frontend, pull requests merged in 2021-04, with the labels that each got.

#23 docs(#116): update in README.md and pull_request_template.md
  .github/pull_request_template.md
  README.md
  assets/Carlos.jpeg
  assets/Ciro.jpeg
  assets/Erick.jpeg
  assets/Gabriel.jpeg
  assets/Guilherme.jpeg
  assets/Paulo.jpeg
  lib/models/user.dart
Labels: Back-end, Front-end, Sprint 7, documentation

#24 Conexão Front e Back
  lib/api.dart
  lib/controllers/userController.dart
  lib/controllers/userController.g.dart
  lib/globals.dart
  lib/main.dart
  lib/screens/LoginScreen.dart
  lib/screens/MyWidgets.dart
  lib/screens/RegisterScreen.dart
  lib/screens/adminConfig_screen.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: Back-end, Front-end, Sprint 7

#25 docs(#116): adding pictures and tamplate's title.
  .github/pull_request_template.md
  README.md
Labels: Back-end, Front-end, Sprint 7, documentation

#37 feat(#146): adding help screen.
  lib/screens/GeneralScreen.dart
  lib/screens/HelpScreen.dart
  lib/screens/LoginScreen.dart
  lib/screens/MainScreen.dart
  lib/screens/MyWidgets.dart
Labels: Development, Front-end, Sprint 10
